<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3petclinic"
 *
 * Auto generated by Extension Builder 2017-11-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'T3Petclinic',
    'description' => 'TYPO3 Petclinic - A Fluid and Extbase Version of Spring Petclinic',
    'category' => 'plugin',
    'author' => 'Thomas Woehlke',
    'author_email' => 'thomas@woehlke.org',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
